/** IATA → the IANA zone the airport keeps its clocks in.
 *
 * Same table the app uses (assets/data/airport-timezones.json, regenerated by
 * scripts/build-airport-timezones.mjs) — imported rather than copied so the
 * two can't drift.
 *
 * The server writes push copy about flights it will never read back: a
 * follower in Bengaluru watching a Stockholm departure wants 12:25, the time
 * their traveler is actually living by, and so does the traveler. Neither is
 * served by the reader's own clock, and "12:25 UTC" only makes them do the
 * arithmetic themselves.
 */

import zoneData from '../assets/data/airport-timezones.json';

let zones: Record<string, string> | null = null;

export function airportZone(iata: string | null | undefined): string | null {
  if (!iata) return null;
  if (!zones) {
    zones = {};
    for (const [zone, codes] of Object.entries(zoneData as Record<string, string>)) {
      for (const code of codes.split(',')) zones[code] = zone;
    }
  }
  return zones[iata.trim().toUpperCase()] ?? null;
}

/** 'YYYY-MM-DD' as the airport's own calendar reads an instant. Provider
 * lookups are keyed on the flight's LOCAL date, so slicing a stored UTC
 * timestamp asks about the wrong day whenever local and UTC midnight fall
 * apart — a 00:15 departure from Auckland is 11:15Z the day before. */
export function flightDay(iso: string, iata: string | null | undefined): string {
  const zone = airportZone(iata);
  if (!zone || !/(Z|[+-]\d\d:?\d\d)$/.test(iso)) return iso.slice(0, 10);
  const at = new Date(iso);
  if (Number.isNaN(at.getTime())) return iso.slice(0, 10);
  try {
    return new Intl.DateTimeFormat('en-CA', {
      timeZone: zone,
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    }).format(at);
  } catch {
    return iso.slice(0, 10);
  }
}
