/** IATA → the IANA zone the airport keeps its clocks in.
 *
 * Same table the app uses (assets/data/airport-timezones.json, regenerated by
 * scripts/build-airport-timezones.mjs) — imported rather than copied so the
 * two can't drift.
 *
 * The server writes push copy about flights it will never read back: a
 * follower in Bengaluru watching a Stockholm departure wants 12:25, the time
 * their traveler is actually living by, and so does the traveler. Neither is
 * served by the reader's own clock, and "12:25 UTC" only makes them do the
 * arithmetic themselves.
 */

import zoneData from '../assets/data/airport-timezones.json';

let zones: Record<string, string> | null = null;

export function airportZone(iata: string | null | undefined): string | null {
  if (!iata) return null;
  if (!zones) {
    zones = {};
    for (const [zone, codes] of Object.entries(zoneData as Record<string, string>)) {
      for (const code of codes.split(',')) zones[code] = zone;
    }
  }
  return zones[iata.trim().toUpperCase()] ?? null;
}

/** 'YYYY-MM-DD' as the airport's own calendar reads an instant. Provider
 * lookups are keyed on the flight's LOCAL date, so slicing a stored UTC
 * timestamp asks about the wrong day whenever local and UTC midnight fall
 * apart — a 00:15 departure from Auckland is 11:15Z the day before. */
export function flightDay(iso: string, iata: string | null | undefined): string {
  const zone = airportZone(iata);
  if (!zone || !/(Z|[+-]\d\d:?\d\d)$/.test(iso)) return iso.slice(0, 10);
  const at = new Date(iso);
  if (Number.isNaN(at.getTime())) return iso.slice(0, 10);
  try {
    return new Intl.DateTimeFormat('en-CA', {
      timeZone: zone,
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    }).format(at);
  } catch {
    return iso.slice(0, 10);
  }
}

const ZONED = /(Z|[+-]\d\d:?\d\d)$/;
const WALL = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})/;

/** Offset of `zone` from UTC at `utcMs`, via the same Intl round-trip the app
 * uses (src/services/dates.ts#zoneOffsetMs). */
function zoneOffsetMs(utcMs: number, zone: string): number {
  try {
    const parts = new Intl.DateTimeFormat('en-CA', {
      timeZone: zone,
      hour12: false,
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
    }).formatToParts(new Date(utcMs));
    const at = (type: string) => Number(parts.find((p) => p.type === type)?.value);
    const asUtc = Date.UTC(at('year'), at('month') - 1, at('day'), at('hour') % 24, at('minute'), at('second'));
    return Number.isFinite(asUtc) ? asUtc - utcMs : 0;
  } catch {
    return 0;
  }
}

/** A stored flight time as an instant (ms) — the server twin of
 * src/services/dates.ts#flightInstant. Zoned strings parse as they are; a
 * bare wall clock ("2026-09-09T04:15:00", how manual rows are stored) is
 * pinned to its airport's zone instead of being read as UTC, which is what
 * `Date.parse` silently does on the server and drifts every countdown,
 * progress bar and poll schedule by the airport's offset. NaN when the
 * string can't be placed. */
export function flightInstant(iso: string | null | undefined, iata: string | null | undefined): number {
  if (!iso) return NaN;
  if (ZONED.test(iso)) return Date.parse(iso);
  const wall = WALL.exec(iso);
  const zone = airportZone(iata);
  if (!wall || !zone) return Date.parse(iso);
  const asUtc = Date.UTC(+wall[1], +wall[2] - 1, +wall[3], +wall[4], +wall[5]);
  if (!Number.isFinite(asUtc)) return NaN;
  // Twice: the offset depends on the instant, and the first guess can land
  // on the wrong side of a daylight-saving switch.
  let ms = asUtc - zoneOffsetMs(asUtc, zone);
  ms = asUtc - zoneOffsetMs(ms, zone);
  return ms;
}
