/** Lookup over the bundled OurAirports extract (assets/data/airports.json,
 * regenerated by scripts/build-airports.mjs). Bundled rather than served so
 * manual trip entry works offline — this app gets used on planes. */

// Relative import (not @/assets) so jest resolves it without extra config.
import data from '../../assets/data/airports.json';

/** [lat, lon, ISO country, city] — the compact tuple the build script emits. */
type AirportTuple = [number, number, string, string];

const AIRPORTS = data as unknown as Record<string, AirportTuple>;

export interface Airport {
  iata: string;
  lat: number;
  lon: number;
  country: string;
  city: string;
}

function toAirport(iata: string, tuple: AirportTuple): Airport {
  const [lat, lon, country, city] = tuple;
  return { iata, lat, lon, country, city };
}

export function getAirport(iata: string): Airport | undefined {
  const code = iata.trim().toUpperCase();
  const tuple = AIRPORTS[code];
  return tuple ? toAirport(code, tuple) : undefined;
}

/** True when the input is a 3-letter code present in the dataset. */
export function isValidIata(input: string): boolean {
  const code = input.trim().toUpperCase();
  return /^[A-Z]{3}$/.test(code) && code in AIRPORTS;
}

/** Prefix match on the IATA code plus substring match on the city name. */
export function searchAirports(query: string, limit = 6): Airport[] {
  const q = query.trim().toUpperCase();
  if (!q) return [];

  const results: Airport[] = [];
  const exact = AIRPORTS[q];
  if (exact) results.push(toAirport(q, exact));

  for (const [iata, tuple] of Object.entries(AIRPORTS)) {
    if (results.length >= limit) break;
    if (iata === q) continue;
    if (iata.startsWith(q) || tuple[3].toUpperCase().includes(q)) {
      results.push(toAirport(iata, tuple));
    }
  }
  return results.slice(0, limit);
}
