/** Lookup over the bundled OurAirports extract (assets/data/airports.json,
 * regenerated by scripts/build-airports.mjs). Bundled rather than served so
 * manual trip entry works offline — this app gets used on planes. */

// Relative import (not @/assets) so jest resolves it without extra config.
import data from '../../assets/data/airports.json';

import { COUNTRY_NAMES } from '@/constants/countries';

/** [lat, lon, ISO country, city, rank?] — the compact tuple the build script
 * emits; the trailing rank (2 = curated major hub, 1 = large_airport,
 * omitted = medium) orders search suggestions. */
type AirportTuple = [number, number, string, string, (1 | 2)?];

const AIRPORTS = data as unknown as Record<string, AirportTuple>;

export interface Airport {
  iata: string;
  lat: number;
  lon: number;
  country: string;
  city: string;
}

function toAirport(iata: string, tuple: AirportTuple): Airport {
  const [lat, lon, country, city] = tuple;
  return { iata, lat, lon, country, city };
}

/** "FI" → "Finland"; falls back to the code itself for unknown values. */
export function countryName(isoCode: string): string {
  return COUNTRY_NAMES[isoCode] ?? isoCode;
}

export function getAirport(iata: string): Airport | undefined {
  const code = iata.trim().toUpperCase();
  const tuple = AIRPORTS[code];
  return tuple ? toAirport(code, tuple) : undefined;
}

/** True when the input is a 3-letter code present in the dataset. */
export function isValidIata(input: string): boolean {
  const code = input.trim().toUpperCase();
  return /^[A-Z]{3}$/.test(code) && code in AIRPORTS;
}

/** Ranked search: exact code, then code prefixes, then cities with a word
 * starting on the query, then bare substrings. Tiers matter — a flat scan
 * let alphabetically early substring hits (ABE, "Bethlehem") fill the list
 * before the obvious code match (HEL) was ever reached. */
export function searchAirports(query: string, limit = 6): Airport[] {
  const q = query.trim().toUpperCase();
  if (!q) return [];

  const exact = AIRPORTS[q];
  const results = exact ? [toAirport(q, exact)] : [];
  // Each tier keeps [airport, rank] so major hubs (LAX) sort above large
  // airports (LAD Luanda) above small ones sharing the prefix (LAA Lamar),
  // alphabetical within a rank (Array.sort is stable).
  const codePrefix: [Airport, number][] = [];
  const cityWord: [Airport, number][] = [];
  const citySubstring: [Airport, number][] = [];

  for (const [iata, tuple] of Object.entries(AIRPORTS)) {
    if (iata === q) continue;
    const city = tuple[3].toUpperCase();
    if (iata.startsWith(q)) {
      codePrefix.push([toAirport(iata, tuple), tuple[4] ?? 0]);
    } else if (city.split(/[^A-Z]+/).some((w) => w.startsWith(q))) {
      cityWord.push([toAirport(iata, tuple), tuple[4] ?? 0]);
    } else if (city.includes(q)) {
      citySubstring.push([toAirport(iata, tuple), tuple[4] ?? 0]);
    }
  }

  const ranked = (tier: [Airport, number][]) =>
    tier.sort((a, b) => b[1] - a[1]).map(([airport]) => airport);

  return results
    .concat(ranked(codePrefix), ranked(cityWord), ranked(citySubstring))
    .slice(0, limit);
}

/** 2 = curated major hub, 1 = large airport, 0 = everything else. The tier
 * lets document parsing trust a bare three-letter token as an airport code
 * only when it names somewhere a flight plausibly goes. */
export function airportRank(iata: string): 0 | 1 | 2 {
  const tuple = AIRPORTS[iata.trim().toUpperCase()];
  return tuple?.[4] ?? 0;
}

let hubCache: Airport[] | null = null;

/** The curated major hubs (rank 2) — a couple hundred airports whose city
 * names are distinctive enough to spot in itinerary text ("DOHA HAMAD
 * INTERNATIONAL" → DOH) without turning every "Nice" into an airport. */
export function hubAirports(): Airport[] {
  if (!hubCache) {
    hubCache = Object.entries(AIRPORTS)
      .filter(([, tuple]) => tuple[4] === 2)
      .map(([iata, tuple]) => toAirport(iata, tuple));
  }
  return hubCache;
}
