/** Lookup over the bundled OurAirports extract (assets/data/airports.json,
 * regenerated by scripts/build-airports.mjs). Bundled rather than served so
 * manual trip entry works offline — this app gets used on planes. */

// Relative import (not @/assets) so jest resolves it without extra config.
import data from '../../assets/data/airports.json';

import { COUNTRY_NAMES } from '@/constants/countries';

/** [lat, lon, ISO country, city, large?] — the compact tuple the build script
 * emits; the trailing 1 (omitted for medium airports) marks large_airport. */
type AirportTuple = [number, number, string, string, 1?];

const AIRPORTS = data as unknown as Record<string, AirportTuple>;

export interface Airport {
  iata: string;
  lat: number;
  lon: number;
  country: string;
  city: string;
}

function toAirport(iata: string, tuple: AirportTuple): Airport {
  const [lat, lon, country, city] = tuple;
  return { iata, lat, lon, country, city };
}

/** "FI" → "Finland"; falls back to the code itself for unknown values. */
export function countryName(isoCode: string): string {
  return COUNTRY_NAMES[isoCode] ?? isoCode;
}

export function getAirport(iata: string): Airport | undefined {
  const code = iata.trim().toUpperCase();
  const tuple = AIRPORTS[code];
  return tuple ? toAirport(code, tuple) : undefined;
}

/** True when the input is a 3-letter code present in the dataset. */
export function isValidIata(input: string): boolean {
  const code = input.trim().toUpperCase();
  return /^[A-Z]{3}$/.test(code) && code in AIRPORTS;
}

/** Ranked search: exact code, then code prefixes, then cities with a word
 * starting on the query, then bare substrings. Tiers matter — a flat scan
 * let alphabetically early substring hits (ABE, "Bethlehem") fill the list
 * before the obvious code match (HEL) was ever reached. */
export function searchAirports(query: string, limit = 6): Airport[] {
  const q = query.trim().toUpperCase();
  if (!q) return [];

  const exact = AIRPORTS[q];
  const results = exact ? [toAirport(q, exact)] : [];
  // Each tier keeps [airport, isLarge] so large airports (HEL) sort above
  // small ones sharing the prefix (HEH) without losing alphabetical order.
  const codePrefix: [Airport, number][] = [];
  const cityWord: [Airport, number][] = [];
  const citySubstring: [Airport, number][] = [];

  for (const [iata, tuple] of Object.entries(AIRPORTS)) {
    if (iata === q) continue;
    const city = tuple[3].toUpperCase();
    if (iata.startsWith(q)) {
      codePrefix.push([toAirport(iata, tuple), tuple[4] ?? 0]);
    } else if (city.split(/[^A-Z]+/).some((w) => w.startsWith(q))) {
      cityWord.push([toAirport(iata, tuple), tuple[4] ?? 0]);
    } else if (city.includes(q)) {
      citySubstring.push([toAirport(iata, tuple), tuple[4] ?? 0]);
    }
  }

  const ranked = (tier: [Airport, number][]) =>
    tier.sort((a, b) => b[1] - a[1]).map(([airport]) => airport);

  return results
    .concat(ranked(codePrefix), ranked(cityWord), ranked(citySubstring))
    .slice(0, limit);
}
