/** Pure map-geometry helpers for the World tab — UI-free, testable.
 *
 * Projection constants come from assets/data/world-map.json (regenerated by
 * scripts/build-world-map.mjs) so the route arcs can never drift from the
 * land silhouette they're drawn over. */

// Relative import (not @/assets) so jest resolves it without extra config.
import worldMap from '../../assets/data/world-map.json';

import { getAirport, type Airport } from '@/services/airports';
import type { JourneyRow } from '@/services/journeys';

export const WORLD = worldMap as {
  width: number;
  height: number;
  latTop: number;
  latBottom: number;
  land: string;
};

export interface MapPoint {
  x: number;
  y: number;
}

/** Equirectangular projection into the world-map viewBox. Latitudes outside
 * the crop (polar great-circle peaks) clamp to the map edge. */
export function project(lat: number, lon: number): MapPoint {
  const clamped = Math.min(WORLD.latTop, Math.max(WORLD.latBottom, lat));
  return {
    x: ((lon + 180) / 360) * WORLD.width,
    y: ((WORLD.latTop - clamped) / (WORLD.latTop - WORLD.latBottom)) * WORLD.height,
  };
}

const toRad = (deg: number) => (deg * Math.PI) / 180;
const toDeg = (rad: number) => (rad * 180) / Math.PI;

const EARTH_RADIUS_KM = 6371;

/** Great-circle distance in whole kilometres between two coordinates. */
export function haversineKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const dLat = toRad(lat2 - lat1);
  const dLon = toRad(lon2 - lon1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLon / 2) ** 2;
  return Math.round(2 * EARTH_RADIUS_KM * Math.asin(Math.sqrt(a)));
}

/** Sample the great circle between two coordinates (~one point per 2° of
 * arc), returned as [lat, lon] pairs including both endpoints. */
export function greatCircle(
  fromLat: number,
  fromLon: number,
  toLat: number,
  toLon: number,
): [number, number][] {
  const φ1 = toRad(fromLat);
  const λ1 = toRad(fromLon);
  const φ2 = toRad(toLat);
  const λ2 = toRad(toLon);
  const a = [Math.cos(φ1) * Math.cos(λ1), Math.cos(φ1) * Math.sin(λ1), Math.sin(φ1)];
  const b = [Math.cos(φ2) * Math.cos(λ2), Math.cos(φ2) * Math.sin(λ2), Math.sin(φ2)];
  const dot = Math.min(1, Math.max(-1, a[0] * b[0] + a[1] * b[1] + a[2] * b[2]));
  const angle = Math.acos(dot);

  // Degenerate spherical interpolation: co-located or antipodal endpoints
  // (where the great circle is ambiguous anyway) fall back to a straight hop.
  if (Math.sin(angle) < 1e-6) {
    return [
      [fromLat, fromLon],
      [toLat, toLon],
    ];
  }

  const steps = Math.max(8, Math.ceil(toDeg(angle) / 2));
  const points: [number, number][] = [];
  for (let i = 0; i <= steps; i += 1) {
    const t = i / steps;
    const s1 = Math.sin((1 - t) * angle) / Math.sin(angle);
    const s2 = Math.sin(t * angle) / Math.sin(angle);
    const x = s1 * a[0] + s2 * b[0];
    const y = s1 * a[1] + s2 * b[1];
    const z = s1 * a[2] + s2 * b[2];
    points.push([toDeg(Math.asin(z)), toDeg(Math.atan2(y, x))]);
  }
  return points;
}

/** Coordinate pair in react-native-maps shape. */
export interface LatLng {
  latitude: number;
  longitude: number;
}

/** Initial compass bearing from `a` to `b` in degrees clockwise from north.
 * Mercator is conformal, so this is also the on-screen angle of the arc. */
export function bearing(a: LatLng, b: LatLng): number {
  const φ1 = toRad(a.latitude);
  const φ2 = toRad(b.latitude);
  const Δλ = toRad(b.longitude - a.longitude);
  const y = Math.sin(Δλ) * Math.cos(φ2);
  const x = Math.cos(φ1) * Math.sin(φ2) - Math.sin(φ1) * Math.cos(φ2) * Math.cos(Δλ);
  return (toDeg(Math.atan2(y, x)) + 360) % 360;
}

/** A polyline point with an optional per-point alpha (0–1) for gradient strokes. */
export interface ShadedLatLng extends LatLng {
  alpha?: number;
}

/** Split a sequence of coordinates wherever it wraps the antimeridian, so no
 * segment draws the long way around the globe. Each side ends exactly at
 * ±180°, with latitude (and alpha) interpolated to the edge. */
export function splitAtAntimeridian<T extends ShadedLatLng>(points: T[]): T[][] {
  const segments: T[][] = [[]];
  for (let i = 0; i < points.length; i += 1) {
    const point = points[i];
    if (i > 0) {
      const prev = points[i - 1];
      if (Math.abs(point.longitude - prev.longitude) > 180) {
        // Interpolate the ±180° crossing so both segments reach the edge.
        const unwrapped = point.longitude + (point.longitude < prev.longitude ? 360 : -360);
        const t = (180 * Math.sign(prev.longitude) - prev.longitude) / (unwrapped - prev.longitude);
        const latitude = prev.latitude + (point.latitude - prev.latitude) * t;
        const alpha =
          prev.alpha != null && point.alpha != null
            ? prev.alpha + (point.alpha - prev.alpha) * t
            : undefined;
        segments[segments.length - 1].push({
          ...prev,
          latitude,
          longitude: 180 * Math.sign(prev.longitude),
          alpha,
        });
        segments.push([{ ...point, latitude, longitude: 180 * Math.sign(point.longitude), alpha }]);
      }
    }
    segments[segments.length - 1].push(point);
  }
  return segments.filter((segment) => segment.length > 1);
}

/** Great-circle arc as map-SDK polyline coordinates. Usually one segment;
 * arcs that wrap the antimeridian (LAX–NRT) split into two, each ending
 * exactly at ±180° so neither polyline draws the long way around the globe. */
export function arcCoordinates(from: Airport, to: Airport): LatLng[][] {
  return splitAtAntimeridian(
    greatCircle(from.lat, from.lon, to.lat, to.lon).map(([latitude, longitude]) => ({
      latitude,
      longitude,
    })),
  );
}

/** The arc's raw samples in drawing order, undoing the antimeridian split
 * (the two edge points collapse back into one hop). Samples are evenly spaced
 * in angle, so a fractional index is a fraction of the arc. */
function arcSamples(segments: LatLng[][]): LatLng[] {
  const samples: LatLng[] = [];
  for (const segment of segments) {
    for (const point of segment) {
      const prev = samples[samples.length - 1];
      if (prev && prev.latitude === point.latitude && Math.abs(prev.longitude) === 180) continue;
      samples.push(point);
    }
  }
  return samples;
}

/** Whether two consecutive samples straddle the antimeridian — linear
 * interpolation between them would cross the whole map. */
const wraps = (a: LatLng, b: LatLng) => Math.abs(a.longitude - b.longitude) > 180;

/** The point a fraction `t` (0–1) along the samples, plus the arc's heading
 * there. Between a wrapping pair the point snaps to the nearer sample. */
function alongSamples(samples: LatLng[], t: number): { coordinate: LatLng; heading: number } {
  const last = samples.length - 1;
  const position = Math.min(Math.max(t, 0), 1) * last;
  const i = Math.min(Math.floor(position), last - 1);
  const f = position - i;
  const a = samples[i];
  const b = samples[i + 1];
  const coordinate = wraps(a, b)
    ? f < 0.5
      ? a
      : b
    : {
        latitude: a.latitude + (b.latitude - a.latitude) * f,
        longitude: a.longitude + (b.longitude - a.longitude) * f,
      };
  return { coordinate, heading: bearing(a, b) };
}

/** Where along an arc a fraction `t` (0 = `from`, 1 = `to`) falls, and the
 * direction of travel there. Used to place and rotate route planes. */
export function pointAlong(segments: LatLng[][], t: number): { coordinate: LatLng; heading: number } {
  return alongSamples(arcSamples(segments), t);
}

/** `arcCoordinates` projected into the SVG world map (the web fallback). */
export function arcSegments(from: Airport, to: Airport): MapPoint[][] {
  return arcCoordinates(from, to).map((segment) =>
    segment.map((c) => project(c.latitude, c.longitude)),
  );
}

/** `arcSegments` rendered as SVG path `d` strings. */
export function arcPaths(from: Airport, to: Airport): string[] {
  return arcSegments(from, to).map((points) =>
    points.map((p, i) => `${i === 0 ? 'M' : 'L'}${p.x.toFixed(2)} ${p.y.toFixed(2)}`).join(''),
  );
}

/** One journey on a route pair, as the World tab's detail card lists it. */
export interface RouteLeg {
  id: string;
  from: Airport;
  to: Airport;
  number: string;
  carrier: string;
  scheduledDeparture: string;
  /** Departure is in the past. */
  flown: boolean;
}

export interface GeoRoute {
  /** Direction-insensitive pair key, e.g. "DXB-LAX". */
  key: string;
  /** Origin of the first journey seen on the pair (the arc itself is
   * symmetric — both directions trace the same great circle). */
  from: Airport;
  to: Airport;
  /** How many journeys fly this pair (either direction). */
  count: number;
  /** True when every journey on the pair is still ahead — drawn animated. */
  upcomingOnly: boolean;
  segments: LatLng[][];
  /** Every journey on the pair, earliest departure first. */
  legs: RouteLeg[];
}

/** The plane glyph drawn on a route: its position, heading and which leg it
 * stands for. */
export interface RoutePlane {
  coordinate: LatLng;
  /** Compass heading, degrees clockwise from north. */
  heading: number;
  /** A departure still ahead — the plane waits by its origin and pulses. */
  upcoming: boolean;
  /** The leg the plane represents: the next one to fly, else the latest flown. */
  leg: RouteLeg;
  /** True when `leg` flies from `route.from` to `route.to` (the arc's sample
   * order); false when it flies the pair the other way. */
  forward: boolean;
}

/** How far along the arc an undeparted plane waits: about ORIGIN_OFFSET_KM
 * out, so it reads as "not left yet" without hiding the airport dot, and
 * several departures from one hub fan out by heading instead of stacking.
 * Clamped to a fraction of the arc so a long haul's plane still hugs its
 * origin and a short hop's isn't pushed to the midpoint. */
const ORIGIN_OFFSET_KM = 250;
const ORIGIN_OFFSET_MIN = 0.07;
const ORIGIN_OFFSET_MAX = 0.3;

function originOffset(route: GeoRoute): number {
  const km = haversineKm(route.from.lat, route.from.lon, route.to.lat, route.to.lon);
  return Math.min(ORIGIN_OFFSET_MAX, Math.max(ORIGIN_OFFSET_MIN, ORIGIN_OFFSET_KM / km));
}

/** Where the route's plane sits. Direction comes from the journeys, not the
 * (undirected) pair: the next upcoming leg wins, else the most recent one. */
export function routePlane(route: GeoRoute): RoutePlane {
  const next = route.legs.find((leg) => !leg.flown);
  const leg = next ?? route.legs[route.legs.length - 1];
  const forward = leg.from.iata === route.from.iata;
  const t = next ? originOffset(route) : 0.5;
  const { coordinate, heading } = pointAlong(route.segments, forward ? t : 1 - t);
  return {
    coordinate,
    heading: forward ? heading : (heading + 180) % 360,
    upcoming: next != null,
    leg,
    forward,
  };
}

/** Local map scale at a tap: degrees of longitude / latitude per screen point,
 * the latitude figure taken at the tap's own latitude (Mercator stretches it
 * poleward). */
export interface DegreesPerPoint {
  lon: number;
  lat: number;
}

/** The route whose arc passes within `tolerance` screen points of `tap`, or
 * null. Distances are point-to-segment in a locally flat screen space, which
 * is exact enough within a fingertip. Neither map SDK gives reliable overlay
 * taps (Google needs a fat stroke, Apple needs `tappable` plumbing), so the
 * screen hit-tests routes itself from the map's tap event. */
export function nearestRoute(
  routes: GeoRoute[],
  tap: LatLng,
  scale: DegreesPerPoint,
  tolerance: number,
): string | null {
  const toPoint = (c: LatLng) => {
    const dLon = ((c.longitude - tap.longitude + 540) % 360) - 180;
    return { x: dLon / scale.lon, y: (c.latitude - tap.latitude) / scale.lat };
  };
  let best: string | null = null;
  let bestDistance = tolerance;
  for (const route of routes) {
    for (const segment of route.segments) {
      let a = toPoint(segment[0]);
      for (let i = 1; i < segment.length; i += 1) {
        const b = toPoint(segment[i]);
        const abx = b.x - a.x;
        const aby = b.y - a.y;
        const lengthSq = abx * abx + aby * aby;
        // Projection of the tap (the origin) onto ab, clamped to the segment.
        const t = lengthSq ? Math.min(1, Math.max(0, -(a.x * abx + a.y * aby) / lengthSq)) : 0;
        const px = a.x + abx * t;
        const py = a.y + aby * t;
        const distance = Math.hypot(px, py);
        if (distance < bestDistance) {
          bestDistance = distance;
          best = route.key;
        }
        a = b;
      }
    }
  }
  return best;
}

/** Fraction of the arc the travelling highlight spans. */
export const COMET_LENGTH = 0.28;

/** The bright "comet" that runs along an upcoming route toward its
 * destination: the stretch of arc from `head - COMET_LENGTH` to `head`, both
 * fractions of the arc in the leg's direction of travel. `head` runs from 0
 * to 1 + COMET_LENGTH so the tail clears the destination before the next
 * pass. Each point carries an alpha ramping 0 at the tail to 1 at the head;
 * antimeridian-wrapping stretches come back split. */
export function cometSegments(segments: LatLng[][], forward: boolean, head: number): ShadedLatLng[][] {
  const samples = arcSamples(segments);
  if (!forward) samples.reverse();
  const last = samples.length - 1;
  const t0 = Math.max(0, head - COMET_LENGTH);
  const t1 = Math.min(1, head);
  if (t1 - t0 < 0.005) return [];

  const alphaAt = (t: number) => (t - (head - COMET_LENGTH)) / COMET_LENGTH;
  const points: ShadedLatLng[] = [{ ...alongSamples(samples, t0).coordinate, alpha: alphaAt(t0) }];
  const first = Math.floor(t0 * last) + 1;
  const stop = Math.ceil(t1 * last) - 1;
  for (let i = first; i <= stop; i += 1) {
    points.push({ ...samples[i], alpha: alphaAt(i / last) });
  }
  points.push({ ...alongSamples(samples, t1).coordinate, alpha: alphaAt(t1) });
  return splitAtAntimeridian(points);
}

export interface GeoAirport extends Airport {
  /** Journeys touching this airport — sizes the dot. */
  count: number;
}

/** The journey fields the map needs — a DB row, or the demo journey shaped
 * like one. */
export type RouteSource = Pick<
  JourneyRow,
  'id' | 'fromCode' | 'toCode' | 'number' | 'carrier' | 'scheduledDeparture'
>;

export interface WorldRoutesData {
  routes: GeoRoute[];
  airports: GeoAirport[];
  /** Sparse samples of everything drawn — arcs bow poleward past their
   * endpoints, so the initial camera fit must cover these, not just the
   * airports. */
  fitCoords: LatLng[];
}

/** Collapse journeys into distinct route arcs + visited airports. Rows whose
 * codes aren't in the bundled airport set (manual train/bus entries with
 * non-IATA codes) are skipped — no coordinates, nothing to draw. */
export function buildWorldRoutes(rows: RouteSource[], now: Date): WorldRoutesData {
  const routes = new Map<string, GeoRoute>();
  const airports = new Map<string, GeoAirport>();
  const fitCoords: LatLng[] = [];

  for (const row of rows) {
    const from = getAirport(row.fromCode);
    const to = getAirport(row.toCode);
    if (!from || !to || from.iata === to.iata) continue;

    const flown = Date.parse(row.scheduledDeparture) <= now.getTime();
    for (const airport of [from, to]) {
      const entry = airports.get(airport.iata);
      if (entry) entry.count += 1;
      else airports.set(airport.iata, { ...airport, count: 1 });
    }

    const leg: RouteLeg = {
      id: row.id,
      from,
      to,
      number: row.number,
      carrier: row.carrier,
      scheduledDeparture: row.scheduledDeparture,
      flown,
    };
    const key = [from.iata, to.iata].sort().join('-');
    const route = routes.get(key);
    if (route) {
      route.count += 1;
      route.upcomingOnly = route.upcomingOnly && !flown;
      route.legs.push(leg);
    } else {
      const segments = arcCoordinates(from, to);
      for (const segment of segments) {
        for (let i = 0; i < segment.length; i += 4) fitCoords.push(segment[i]);
        fitCoords.push(segment[segment.length - 1]);
      }
      routes.set(key, { key, from, to, count: 1, upcomingOnly: !flown, segments, legs: [leg] });
    }
  }

  for (const route of routes.values()) {
    route.legs.sort((a, b) => a.scheduledDeparture.localeCompare(b.scheduledDeparture));
  }
  return { routes: [...routes.values()], airports: [...airports.values()], fitCoords };
}

// —— SVG derivations, used by the web fallback map ——

export interface MapRoute extends Omit<GeoRoute, 'segments'> {
  paths: string[];
}

export interface MapAirport extends Airport, MapPoint {
  count: number;
}

export interface WorldMapData {
  routes: MapRoute[];
  airports: MapAirport[];
  fitPoints: MapPoint[];
}

/** `buildWorldRoutes` projected into the SVG world map. */
export function buildWorldMap(rows: RouteSource[], now: Date): WorldMapData {
  const { routes, airports, fitCoords } = buildWorldRoutes(rows, now);
  return {
    routes: routes.map(({ segments, ...route }) => ({
      ...route,
      paths: segments.map((points) =>
        points
          .map((c, i) => {
            const p = project(c.latitude, c.longitude);
            return `${i === 0 ? 'M' : 'L'}${p.x.toFixed(2)} ${p.y.toFixed(2)}`;
          })
          .join(''),
      ),
    })),
    airports: airports.map((airport) => ({ ...airport, ...project(airport.lat, airport.lon) })),
    fitPoints: fitCoords.map((c) => project(c.latitude, c.longitude)),
  };
}

export interface ViewBox {
  x: number;
  y: number;
  width: number;
  height: number;
}

/** Smallest viewBox with the viewport's aspect ratio containing every point
 * (plus `pad`, a fraction of the span), clamped inside the world map and
 * never zoomed past `minWidth`. Falls back to the whole map with no points.
 * Always returns a box with the viewport's aspect ratio — the pan/zoom math
 * in the World screen relies on a single px-per-map-unit scale factor. */
export function fitViewBox(
  points: MapPoint[],
  viewAspect: number,
  pad = 0.25,
  minWidth = WORLD.width / 8,
): ViewBox {
  if (viewAspect <= 0) return { x: 0, y: 0, width: WORLD.width, height: WORLD.height };
  if (!points.length) {
    // Whole world, letterboxed to the viewport: extra height splits into sea
    // above and below the map (the sea backdrop extends past the crop).
    const height = WORLD.width / viewAspect;
    return { x: 0, y: (WORLD.height - height) / 2, width: WORLD.width, height };
  }

  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  for (const p of points) {
    minX = Math.min(minX, p.x);
    minY = Math.min(minY, p.y);
    maxX = Math.max(maxX, p.x);
    maxY = Math.max(maxY, p.y);
  }
  const spanX = maxX - minX;
  const spanY = maxY - minY;
  let width = Math.max(minWidth, spanX * (1 + pad * 2), spanY * (1 + pad * 2) * viewAspect);
  width = Math.min(width, WORLD.width);
  const height = width / viewAspect;

  const centerX = (minX + maxX) / 2;
  const centerY = (minY + maxY) / 2;
  const x = Math.min(Math.max(centerX - width / 2, 0), WORLD.width - width);
  // A wide viewport can demand more height than the map has — center overflow.
  const y =
    height >= WORLD.height
      ? (WORLD.height - height) / 2
      : Math.min(Math.max(centerY - height / 2, 0), WORLD.height - height);
  return { x, y, width, height };
}
