/** Pure map-geometry helpers for the World tab — UI-free, testable.
 *
 * Projection constants come from assets/data/world-map.json (regenerated by
 * scripts/build-world-map.mjs) so the route arcs can never drift from the
 * land silhouette they're drawn over. */

// Relative import (not @/assets) so jest resolves it without extra config.
import worldMap from '../../assets/data/world-map.json';

import { getAirport, type Airport } from '@/services/airports';
import type { JourneyRow } from '@/services/journeys';

export const WORLD = worldMap as {
  width: number;
  height: number;
  latTop: number;
  latBottom: number;
  land: string;
};

export interface MapPoint {
  x: number;
  y: number;
}

/** Equirectangular projection into the world-map viewBox. Latitudes outside
 * the crop (polar great-circle peaks) clamp to the map edge. */
export function project(lat: number, lon: number): MapPoint {
  const clamped = Math.min(WORLD.latTop, Math.max(WORLD.latBottom, lat));
  return {
    x: ((lon + 180) / 360) * WORLD.width,
    y: ((WORLD.latTop - clamped) / (WORLD.latTop - WORLD.latBottom)) * WORLD.height,
  };
}

const toRad = (deg: number) => (deg * Math.PI) / 180;
const toDeg = (rad: number) => (rad * 180) / Math.PI;

const EARTH_RADIUS_KM = 6371;

/** Great-circle distance in whole kilometres between two coordinates. */
export function haversineKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const dLat = toRad(lat2 - lat1);
  const dLon = toRad(lon2 - lon1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLon / 2) ** 2;
  return Math.round(2 * EARTH_RADIUS_KM * Math.asin(Math.sqrt(a)));
}

/** Sample the great circle between two coordinates (~one point per 2° of
 * arc), returned as [lat, lon] pairs including both endpoints. */
export function greatCircle(
  fromLat: number,
  fromLon: number,
  toLat: number,
  toLon: number,
): [number, number][] {
  const φ1 = toRad(fromLat);
  const λ1 = toRad(fromLon);
  const φ2 = toRad(toLat);
  const λ2 = toRad(toLon);
  const a = [Math.cos(φ1) * Math.cos(λ1), Math.cos(φ1) * Math.sin(λ1), Math.sin(φ1)];
  const b = [Math.cos(φ2) * Math.cos(λ2), Math.cos(φ2) * Math.sin(λ2), Math.sin(φ2)];
  const dot = Math.min(1, Math.max(-1, a[0] * b[0] + a[1] * b[1] + a[2] * b[2]));
  const angle = Math.acos(dot);

  // Degenerate spherical interpolation: co-located or antipodal endpoints
  // (where the great circle is ambiguous anyway) fall back to a straight hop.
  if (Math.sin(angle) < 1e-6) {
    return [
      [fromLat, fromLon],
      [toLat, toLon],
    ];
  }

  const steps = Math.max(8, Math.ceil(toDeg(angle) / 2));
  const points: [number, number][] = [];
  for (let i = 0; i <= steps; i += 1) {
    const t = i / steps;
    const s1 = Math.sin((1 - t) * angle) / Math.sin(angle);
    const s2 = Math.sin(t * angle) / Math.sin(angle);
    const x = s1 * a[0] + s2 * b[0];
    const y = s1 * a[1] + s2 * b[1];
    const z = s1 * a[2] + s2 * b[2];
    points.push([toDeg(Math.asin(z)), toDeg(Math.atan2(y, x))]);
  }
  return points;
}

/** Projected polyline(s) for one great-circle arc. Usually a single segment;
 * arcs that wrap the antimeridian (LAX–NRT) come back as two, each extended
 * to its map edge so the line visibly runs off one side and onto the other. */
export function arcSegments(from: Airport, to: Airport): MapPoint[][] {
  const samples = greatCircle(from.lat, from.lon, to.lat, to.lon);
  const segments: MapPoint[][] = [[]];
  for (let i = 0; i < samples.length; i += 1) {
    const [lat, lon] = samples[i];
    if (i > 0) {
      const [prevLat, prevLon] = samples[i - 1];
      if (Math.abs(lon - prevLon) > 180) {
        // Interpolate the ±180° crossing so both segments reach the edge.
        const unwrapped = lon + (lon < prevLon ? 360 : -360);
        const t = (180 * Math.sign(prevLon) - prevLon) / (unwrapped - prevLon);
        const latAtEdge = prevLat + (lat - prevLat) * t;
        segments[segments.length - 1].push(project(latAtEdge, 180 * Math.sign(prevLon)));
        segments.push([project(latAtEdge, 180 * Math.sign(lon))]);
      }
    }
    segments[segments.length - 1].push(project(lat, lon));
  }
  return segments.filter((points) => points.length > 1);
}

/** `arcSegments` rendered as SVG path `d` strings. */
export function arcPaths(from: Airport, to: Airport): string[] {
  return arcSegments(from, to).map((points) =>
    points.map((p, i) => `${i === 0 ? 'M' : 'L'}${p.x.toFixed(2)} ${p.y.toFixed(2)}`).join(''),
  );
}

export interface MapRoute {
  /** Direction-insensitive pair key, e.g. "DXB-LAX". */
  key: string;
  from: Airport;
  to: Airport;
  /** How many journeys fly this pair (either direction). */
  count: number;
  /** True when every journey on the pair is still ahead — drawn dashed. */
  upcomingOnly: boolean;
  paths: string[];
}

export interface MapAirport extends Airport, MapPoint {
  /** Journeys touching this airport — sizes the dot. */
  count: number;
}

export interface WorldMapData {
  routes: MapRoute[];
  airports: MapAirport[];
  /** Sparse samples of everything drawn — arcs bow poleward past their
   * endpoints, so the initial fit must cover these, not just the airports. */
  fitPoints: MapPoint[];
}

/** Collapse journeys into distinct route arcs + visited airports. Rows whose
 * codes aren't in the bundled airport set (manual train/bus entries with
 * non-IATA codes) are skipped — no coordinates, nothing to draw. */
export function buildWorldMap(rows: JourneyRow[], now: Date): WorldMapData {
  const routes = new Map<string, MapRoute>();
  const airports = new Map<string, MapAirport>();
  const fitPoints: MapPoint[] = [];

  for (const row of rows) {
    const from = getAirport(row.fromCode);
    const to = getAirport(row.toCode);
    if (!from || !to || from.iata === to.iata) continue;

    const flown = Date.parse(row.scheduledDeparture) <= now.getTime();
    for (const airport of [from, to]) {
      const entry = airports.get(airport.iata);
      if (entry) entry.count += 1;
      else airports.set(airport.iata, { ...airport, ...project(airport.lat, airport.lon), count: 1 });
    }

    const key = [from.iata, to.iata].sort().join('-');
    const route = routes.get(key);
    if (route) {
      route.count += 1;
      route.upcomingOnly = route.upcomingOnly && !flown;
    } else {
      const segments = arcSegments(from, to);
      for (const segment of segments) {
        for (let i = 0; i < segment.length; i += 4) fitPoints.push(segment[i]);
        fitPoints.push(segment[segment.length - 1]);
      }
      routes.set(key, {
        key,
        from,
        to,
        count: 1,
        upcomingOnly: !flown,
        paths: segments.map((points) =>
          points.map((p, i) => `${i === 0 ? 'M' : 'L'}${p.x.toFixed(2)} ${p.y.toFixed(2)}`).join(''),
        ),
      });
    }
  }

  return { routes: [...routes.values()], airports: [...airports.values()], fitPoints };
}

export interface ViewBox {
  x: number;
  y: number;
  width: number;
  height: number;
}

/** Smallest viewBox with the viewport's aspect ratio containing every point
 * (plus `pad`, a fraction of the span), clamped inside the world map and
 * never zoomed past `minWidth`. Falls back to the whole map with no points.
 * Always returns a box with the viewport's aspect ratio — the pan/zoom math
 * in the World screen relies on a single px-per-map-unit scale factor. */
export function fitViewBox(
  points: MapPoint[],
  viewAspect: number,
  pad = 0.25,
  minWidth = WORLD.width / 8,
): ViewBox {
  if (viewAspect <= 0) return { x: 0, y: 0, width: WORLD.width, height: WORLD.height };
  if (!points.length) {
    // Whole world, letterboxed to the viewport: extra height splits into sea
    // above and below the map (the sea backdrop extends past the crop).
    const height = WORLD.width / viewAspect;
    return { x: 0, y: (WORLD.height - height) / 2, width: WORLD.width, height };
  }

  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  for (const p of points) {
    minX = Math.min(minX, p.x);
    minY = Math.min(minY, p.y);
    maxX = Math.max(maxX, p.x);
    maxY = Math.max(maxY, p.y);
  }
  const spanX = maxX - minX;
  const spanY = maxY - minY;
  let width = Math.max(minWidth, spanX * (1 + pad * 2), spanY * (1 + pad * 2) * viewAspect);
  width = Math.min(width, WORLD.width);
  const height = width / viewAspect;

  const centerX = (minX + maxX) / 2;
  const centerY = (minY + maxY) / 2;
  const x = Math.min(Math.max(centerX - width / 2, 0), WORLD.width - width);
  // A wide viewport can demand more height than the map has — center overflow.
  const y =
    height >= WORLD.height
      ? (WORLD.height - height) / 2
      : Math.min(Math.max(centerY - height / 2, 0), WORLD.height - height);
  return { x, y, width, height };
}
